#include "cereal/gen/cpp/car.capnp.h"
#include "cereal/gen/cpp/log.capnp.h"
#include "alerts.h"

alert::Alert ALERTS[] = {
{ 
  "enable",
  "",
  "",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::NONE,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ENGAGE,
  0.2, 0.0, 0.0, 0.0
},
{ 
  "disable",
  "",
  "",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::NONE,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_DISENGAGE,
  0.2, 0.0, 0.0, 0.0
},
{ 
  "fcw",
  "BRAKE!",
  "Risk of Collision",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::FCW,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  1.0, 2.0, 2.0, 0.0
},
{ 
  "steerSaturated",
  "TAKE CONTROL",
  "Turn Exceeds Steering Limit",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_PROMPT,
  1.0, 2.0, 3.0, 0.0
},
{ 
  "steerTempUnavailable",
  "TAKE CONTROL",
  "Steering Temporarily Unavailable",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING1,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "steerTempUnavailableMute",
  "TAKE CONTROL",
  "Steering Temporarily Unavailable",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.2, 0.2, 0.2, 0.0
},
{ 
  "preDriverDistracted",
  "KEEP EYES ON ROAD: User Appears Distracted",
  "",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::SMALL,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.1, 0.1, 0.75
},
{ 
  "promptDriverDistracted",
  "KEEP EYES ON ROAD",
  "User Appears Distracted",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING2,
  0.1, 0.1, 0.1, 0.0
},
{ 
  "driverDistracted",
  "DISENGAGE IMMEDIATELY",
  "User Was Distracted",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGH,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 0.1, 0.1, 0.0
},
{ 
  "preDriverUnresponsive",
  "TOUCH STEERING WHEEL: No Face Detected",
  "",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::SMALL,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.1, 0.1, 0.75
},
{ 
  "promptDriverUnresponsive",
  "TOUCH STEERING WHEEL",
  "User Is Unresponsive",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING2,
  0.1, 0.1, 0.1, 0.0
},
{ 
  "driverUnresponsive",
  "DISENGAGE IMMEDIATELY",
  "User Was Unresponsive",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGH,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 0.1, 0.1, 0.0
},
{ 
  "driverMonitorOff",
  "DRIVER MONITOR IS UNAVAILABLE",
  "Accuracy Is Low",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.4, 0.0, 4.0, 0.0
},
{ 
  "driverMonitorOn",
  "DRIVER MONITOR IS AVAILABLE",
  "Accuracy Is High",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.4, 0.0, 4.0, 0.0
},
{ 
  "geofence",
  "DISENGAGEMENT REQUIRED",
  "Not in Geofenced Area",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::HIGH,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 0.1, 0.1, 0.0
},
{ 
  "startup",
  "Be ready to take over at any time",
  "Always keep hands on wheel and eyes on road",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 15.0, 0.0
},
{ 
  "startupNoControl",
  "Dashcam mode",
  "Always keep hands on wheel and eyes on road",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 15.0, 0.0
},
{ 
  "startupNoCar",
  "Dashcam mode with unsupported car",
  "Always keep hands on wheel and eyes on road",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 15.0, 0.0
},
{ 
  "ethicalDilemma",
  "TAKE CONTROL IMMEDIATELY",
  "Ethical Dilemma Detected",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  1.0, 3.0, 3.0, 0.0
},
{ 
  "steerTempUnavailableNoEntry",
  "openpilot Unavailable",
  "Steering Temporarily Unavailable",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 0.0, 3.0, 0.0
},
{ 
  "manualRestart",
  "TAKE CONTROL",
  "Resume Driving Manually",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "resumeRequired",
  "STOPPED",
  "Press Resume to Move",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "belowSteerSpeed",
  "TAKE CONTROL",
  "Steer Unavailable Below ",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.4, 0.3, 0.0
},
{ 
  "debugAlert",
  "DEBUG ALERT",
  "",
  cereal::ControlsState::AlertStatus::USER_PROMPT,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.1, 0.1, 0.1, 0.0
},
{ 
  "wrongCarModeNoEntry",
  "openpilot Unavailable",
  "Main Switch Off",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 0.0, 3.0, 0.0
},
{ 
  "dataNeededNoEntry",
  "openpilot Unavailable",
  "Data Needed for Calibration. Upload Drive, Try Again",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 0.0, 3.0, 0.0
},
{ 
  "outOfSpaceNoEntry",
  "openpilot Unavailable",
  "Out of Storage Space",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 0.0, 3.0, 0.0
},
{ 
  "pedalPressedNoEntry",
  "openpilot Unavailable",
  "Pedal Pressed During Attempt",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::BRAKE_PRESSED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "speedTooLowNoEntry",
  "openpilot Unavailable",
  "Speed Too Low",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "brakeHoldNoEntry",
  "openpilot Unavailable",
  "Brake Hold Active",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "parkBrakeNoEntry",
  "openpilot Unavailable",
  "Park Brake Engaged",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "lowSpeedLockoutNoEntry",
  "openpilot Unavailable",
  "Cruise Fault: Restart the Car",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "lowBatteryNoEntry",
  "openpilot Unavailable",
  "Low Battery",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "sensorDataInvalidNoEntry",
  "openpilot Unavailable",
  "No Data from EON Sensors",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "soundsUnavailableNoEntry",
  "openpilot Unavailable",
  "Speaker not found",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "tooDistractedNoEntry",
  "openpilot Unavailable",
  "Distraction Level Too High",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "overheat",
  "TAKE CONTROL IMMEDIATELY",
  "System Overheated",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "wrongGear",
  "TAKE CONTROL IMMEDIATELY",
  "Gear not D",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "calibrationInvalid",
  "TAKE CONTROL IMMEDIATELY",
  "Calibration Invalid: Reposition EON and Recalibrate",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "calibrationIncomplete",
  "TAKE CONTROL IMMEDIATELY",
  "Calibration in Progress",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "doorOpen",
  "TAKE CONTROL IMMEDIATELY",
  "Door Open",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "seatbeltNotLatched",
  "TAKE CONTROL IMMEDIATELY",
  "Seatbelt Unlatched",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "espDisabled",
  "TAKE CONTROL IMMEDIATELY",
  "ESP Off",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "lowBattery",
  "TAKE CONTROL IMMEDIATELY",
  "Low Battery",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "commIssue",
  "TAKE CONTROL IMMEDIATELY",
  "Communication Issue between Processes",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "radarCanError",
  "TAKE CONTROL IMMEDIATELY",
  "Radar Error: Restart the Car",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "radarFault",
  "TAKE CONTROL IMMEDIATELY",
  "Radar Error: Restart the Car",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "posenetInvalid",
  "TAKE CONTROL IMMEDIATELY",
  "Vision Failure: Check Camera View",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  0.1, 2.0, 2.0, 0.0
},
{ 
  "controlsFailed",
  "TAKE CONTROL IMMEDIATELY",
  "Controls Failed",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "controlsMismatch",
  "TAKE CONTROL IMMEDIATELY",
  "Controls Mismatch",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "canError",
  "TAKE CONTROL IMMEDIATELY",
  "CAN Error: Check Connections",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "steerUnavailable",
  "TAKE CONTROL IMMEDIATELY",
  "LKAS Fault: Restart the Car",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "brakeUnavailable",
  "TAKE CONTROL IMMEDIATELY",
  "Cruise Fault: Restart the Car",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "gasUnavailable",
  "TAKE CONTROL IMMEDIATELY",
  "Gas Fault: Restart the Car",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "reverseGear",
  "TAKE CONTROL IMMEDIATELY",
  "Reverse Gear",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "cruiseDisabled",
  "TAKE CONTROL IMMEDIATELY",
  "Cruise Is Off",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "plannerError",
  "TAKE CONTROL IMMEDIATELY",
  "Planner Solution Error",
  cereal::ControlsState::AlertStatus::CRITICAL,
  cereal::ControlsState::AlertSize::FULL,
  alert::Priority::HIGHEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_WARNING_REPEAT,
  2.2, 3.0, 4.0, 0.0
},
{ 
  "noTarget",
  "openpilot Canceled",
  "No close lead car",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::HIGH,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_DISENGAGE,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "speedTooLow",
  "openpilot Canceled",
  "Speed too low",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::HIGH,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_DISENGAGE,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "invalidGiraffeHonda",
  "Invalid Giraffe Configuration",
  "Set 0111 for openpilot. 1011 for stock",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::HIGH,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_DISENGAGE,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "overheatNoEntry",
  "openpilot Unavailable",
  "System overheated",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "wrongGearNoEntry",
  "openpilot Unavailable",
  "Gear not D",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "calibrationInvalidNoEntry",
  "openpilot Unavailable",
  "Calibration Invalid: Reposition EON and Recalibrate",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "calibrationIncompleteNoEntry",
  "openpilot Unavailable",
  "Calibration in Progress",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "doorOpenNoEntry",
  "openpilot Unavailable",
  "Door open",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "seatbeltNotLatchedNoEntry",
  "openpilot Unavailable",
  "Seatbelt unlatched",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "espDisabledNoEntry",
  "openpilot Unavailable",
  "ESP Off",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "geofenceNoEntry",
  "openpilot Unavailable",
  "Not in Geofenced Area",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::MID,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "radarCanErrorNoEntry",
  "openpilot Unavailable",
  "Radar Error: Restart the Car",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "radarFaultNoEntry",
  "openpilot Unavailable",
  "Radar Error: Restart the Car",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "posenetInvalidNoEntry",
  "openpilot Unavailable",
  "Vision Failure: Check Camera View",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "controlsFailedNoEntry",
  "openpilot Unavailable",
  "Controls Failed",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "canErrorNoEntry",
  "openpilot Unavailable",
  "CAN Error: Check Connections",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "steerUnavailableNoEntry",
  "openpilot Unavailable",
  "LKAS Fault: Restart the Car",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "brakeUnavailableNoEntry",
  "openpilot Unavailable",
  "Cruise Fault: Restart the Car",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "gasUnavailableNoEntry",
  "openpilot Unavailable",
  "Gas Error: Restart the Car",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "reverseGearNoEntry",
  "openpilot Unavailable",
  "Reverse Gear",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "cruiseDisabledNoEntry",
  "openpilot Unavailable",
  "Cruise is Off",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "noTargetNoEntry",
  "openpilot Unavailable",
  "No Close Lead Car",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "plannerErrorNoEntry",
  "openpilot Unavailable",
  "Planner Solution Error",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_ERROR,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "invalidGiraffeHondaNoEntry",
  "openpilot Unavailable",
  "Set 0111 for openpilot. 1011 for stock",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_DISENGAGE,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "invalidGiraffeToyotaNoEntry",
  "openpilot Unavailable",
  "Visit comma.ai/tg",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_DISENGAGE,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "commIssueNoEntry",
  "openpilot Unavailable",
  "Communication Issue between Processes",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_DISENGAGE,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "internetConnectivityNeededNoEntry",
  "openpilot Unavailable",
  "Internet Connectivity Needed",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::CHIME_DISENGAGE,
  0.4, 2.0, 3.0, 0.0
},
{ 
  "steerUnavailablePermanent",
  "LKAS Fault: Restart the car to engage",
  "",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::SMALL,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "brakeUnavailablePermanent",
  "Cruise Fault: Restart the car to engage",
  "",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::SMALL,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "lowSpeedLockoutPermanent",
  "Cruise Fault: Restart the car to engage",
  "",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::SMALL,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "calibrationIncompletePermanent",
  "Calibration in Progress: ",
  "Drive Above ",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "invalidGiraffeHondaPermanent",
  "Invalid Giraffe Configuration",
  "Set 0111 for openpilot. 1011 for stock",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "invalidGiraffeToyotaPermanent",
  "Unsupported Giraffe Configuration",
  "Visit comma.ai/tg",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "internetConnectivityNeededPermanent",
  "Internet Connectivity Needed",
  "Check for Updates to Be Able to Engage",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "sensorDataInvalidPermanent",
  "No Data from EON Sensors",
  "Reboot your EON",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "soundsUnavailablePermanent",
  "Speaker not found",
  "Reboot your EON",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::MID,
  alert::Priority::LOW_LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::NONE,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.2, 0.0
},
{ 
  "vehicleModelInvalid",
  "Vehicle Parameter Identification Failed",
  "",
  cereal::ControlsState::AlertStatus::NORMAL,
  cereal::ControlsState::AlertSize::SMALL,
  alert::Priority::LOWEST,
  cereal::CarControl::HUDControl::VisualAlert::STEER_REQUIRED,
  cereal::CarControl::HUDControl::AudibleAlert::NONE,
  0.0, 0.0, 0.1, 0.0
},
};
size_t ALERT_COUNT = sizeof(ALERTS)/sizeof(ALERTS[0]);
